;consider the problem of designing a signal-processing system to study the
;homogenous second-order linear differential equation

;\frac{d^2y}{dt^2} - a\frac{dy}{dt} - by = 0

;the output stream, modeling y, is generated by a network that contains a loop.
;this is because the value of  d^2y/dt^2  depends on the values of  y  and
;dy/dt  and both of these are determined by integrating d^2y/dt^2.  the diagram
;we would like ot encode is shown in figure 3.35. write a procedure  solve-2nd
;that takes as arguments the constant a,b, and dt and the initial values
;y_0,dy_0 for y  and  dy/dt  and generates the stream of successive values for y

;int dy = y dt
;y = 1/b ( ddy - ady )
;dy = 1/a ( ddy - by )
;ddy = ady + by

(define (solve-2nd a b dt y0 dy0)
  (define y (integral (delay dy) y0 dt))
  (define dy (integral (delay ddy) dy0 dt))
  (define ddy (add-streams (stream-scale dy a) (stream-scale y b)))
  y)

